station:
  station_id: "Robot_Workstation"
  cameras:
    high:
      serial_no: "317422076722"
      type: "D435i"
    right_wrist:
      serial_no: "12345678"
      type: "D405"
    left_wrist:
      serial_no: "12345678"
      type: "D405"
  gello:
    left_gello_serial_no: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2S0-if00-port0"
    right_gello_serial_no: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2S0-if00-port0"