station:
  station_id: "Robot_Workstation"
  cameras:
    high:
      serial_no: "12345678"
      type: "D435i"
    right_wrist:
      serial_no: "12345678"
      type: "D405"
    left_wrist:
      serial_no: "12345678"
      type: "D405"